"""Regenerate the measured claims the skill quotes, straight from zoo.json.

    conda run -n ltuili python -m skill.facts

Writes skill/measuredFacts.md.

WHY THIS EXISTS
---------------
SKILL.md is read by a model and quoted at users, so every number in it is a claim.
Numbers typed into a document rot the moment anything is rerun, and this one already
did: it said "14 of the 15 admitted entries are overconfident" and within one sweep the
catalogue held 28 admitted entries, 72 overconfident pairs out of 77, and three
entries that are not overconfident at all.

So the numeric claims are generated from the catalogue by path and SKILL.md points at
the generated file. Rerun this after every zoo rebuild. If the two disagree, the
generated file is right.
"""

import json
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[1]
ZOO_PATH = ROOT / "ili_kaai" / "results" / "zoo.json"
OUT = Path(__file__).resolve().parent / "measuredFacts.md"


def admitted(zoo: Dict) -> List[Dict]:
    return [e for e in zoo["entries"] if e["admitted"]]


def pairs(entries: List[Dict]) -> List[tuple]:
    return [(e, m) for e in entries for m in e["measurements"]]


# An entry at or below this mean R2 does no better than predicting the prior mean.
# Kept identical to skill/query.py MIN_USEFUL_R2 on purpose.
MIN_USEFUL_R2 = 0.05


def accuracy_lines(rows: List[tuple], task: str) -> List[str]:
    """How far apart the entries actually are on one task, per parameter and in the mean.

    Reported two ways on purpose. Quoting one number here was already wrong once: the
    claim "a spread of 0.073" was Omega_m alone across the working entries, while the
    mean over parameters across all entries spans several times that. Both are true of
    different quantities, so both are stated and the outliers are named.
    """
    vals = sorted(((sum(m["r2"]) / len(m["r2"]), e["key"])
                   for e, m in rows if m["task"] == task), reverse=True)
    if not vals:
        return []
    first = sorted(((m["r2"][0], e["key"])
                    for e, m in rows if m["task"] == task), reverse=True)
    out = [f"- On {task}, mean R2 over all parameters runs {vals[-1][0]:+.3f} "
           f"({vals[-1][1]}) to {vals[0][0]:+.3f} ({vals[0][1]}), spread "
           f"{vals[0][0] - vals[-1][0]:.3f}, across {len(vals)} entries."]
    working = [v for v in vals if v[0] > MIN_USEFUL_R2]
    outliers = [v for v in vals if v[0] <= MIN_USEFUL_R2]
    if outliers:
        out.append(f"- That spread is driven by {len(outliers)} entry(s) that carry no "
                   f"information: {', '.join(f'{k} at {v:+.3f}' for v, k in outliers)}.")
    if outliers and len(working) > 1:
        out.append(f"- Excluding those, the remaining {len(working)} entries span "
                   f"{working[-1][0]:+.3f} to {working[0][0]:+.3f}, spread "
                   f"{working[0][0] - working[-1][0]:.3f}.")
    if len(first) > 1:
        fw = [v for v in first if v[0] > MIN_USEFUL_R2]
        if len(fw) > 1:
            out.append(f"- On the first parameter alone, those {len(fw)} entries span "
                       f"{fw[-1][0]:+.3f} to {fw[0][0]:+.3f}, spread "
                       f"{fw[0][0] - fw[-1][0]:.3f}.")
    return out


def cost_spread(rows: List[tuple]) -> tuple:
    vals = [(m["trainSeconds"] + m["inferenceSeconds"], e["key"]) for e, m in rows]
    return (min(vals), max(vals)) if vals else (None, None)


def render(zoo: Dict) -> str:
    entries = admitted(zoo)
    rows = pairs(entries)
    over = [r for r in rows if r[1]["calibrationVerdict"] == "overconfident"]
    calibrated = [r for r in rows if r[1]["calibrationVerdict"] == "calibrated"]
    multi = [r for r in rows if len(r[1]["params"]) > 1]
    hiding = [r for r in rows if r[1]["hidesParameterDisagreement"]]
    mixed = [e for e in entries if e["calibrationVerdict"] == "mixed"]

    cheap, dear = cost_spread(rows)

    out = ["# Measured facts",
           "",
           "GENERATED by skill/facts.py from ili_kaai/results/zoo.json. Do not edit by",
           "hand and do not quote numbers from anywhere else. Regenerate after every",
           "zoo rebuild.",
           "",
           f"Sweeps used: {', '.join(zoo['source']['sweepsUsed'])}."]
    for s in zoo["source"]["sweepsSkipped"]:
        out.append(f"Refused: {s['file']}, {s['reason']}.")

    dims = sorted({len(m["params"]) for _, m in rows})
    out += ["", "## Size", "",
            f"- dim(theta) actually MEASURED here: {dims}. Any recommendation outside "
            f"that range is extrapolation, and query.py warns when the matched task's "
            f"parameter count differs from the query.",
            f"- {len(entries)} admitted entries, {len(rows)} measured entry-task pairs.",
            f"- An entry is admitted per task, so an entry can be admitted on one task "
            f"and unmeasured on another."]

    out += ["", "## Calibration, the thing every recommendation must carry", ""]
    out.append(f"- {len(over)} of {len(rows)} measured pairs are OVERCONFIDENT, "
               f"meaning the error bars come out too small. That is the dangerous "
               f"direction.")
    if calibrated:
        out.append(f"- {len(calibrated)} pairs read calibrated:")
        for e, m in calibrated:
            acc = sum(m["r2"]) / len(m["r2"])
            # A posterior that predicts nothing is wide, and a wide posterior scores
            # well on coverage. Measured: nreLinear reaches coverage 0.69 against a
            # nominal 0.680, better than any real entry, at R2 of about zero. Reading
            # "calibrated" off such a row is the single easiest way to misuse this
            # catalogue, so the row carries the warning rather than the reader.
            flag = ("  <-- CARRIES NO INFORMATION, mean R2 "
                    f"{acc:+.3f}. Being calibrated while useless is not a "
                    "recommendation. Do not quote this as a calibrated entry."
                    if acc <= MIN_USEFUL_R2 else "")
            out.append(f"    - {e['key']} on {m['task']}, coverage "
                       f"{m['coverage68']:.4f} ({m['calibrationSigma']:+.1f} sigma "
                       f"from nominal {zoo['nominal68']}), mean R2 {acc:+.3f}.{flag}")
        useless = [(e, m) for e, m in calibrated
                   if sum(m["r2"]) / len(m["r2"]) <= MIN_USEFUL_R2]
        if useless:
            out.append(f"- WARNING {len(useless)} of those {len(calibrated)} "
                       f"calibrated pairs carry no information at all. Calibration is "
                       f"only meaningful conditional on the posterior being "
                       f"informative, so filter on accuracy BEFORE reading a "
                       f"calibration verdict.")
    if mixed:
        out.append(f"- {len(mixed)} entries are MIXED: their per task verdicts "
                   f"disagree, so no single verdict describes them. "
                   f"{', '.join(e['key'] for e in mixed)}.")
    out.append(f"- The overconfidence threshold is {zoo['calibrationTolerance']:.4f}, "
               f"two sigma of a measured noise band, not a chosen number.")

    out += ["", "## Coverage averaged over parameters hides disagreement", ""]
    out.append(f"- On {len(hiding)} of {len(multi)} multi-parameter pairs the "
               f"parameter mean verdict disagrees with a per parameter verdict.")
    for e, m in hiding:
        detail = ", ".join(f"{p} {c:.4f} {w}" for p, c, w in zip(
            m["params"], m["coverage68ByParam"], m["verdictByParam"]))
        out.append(f"    - {e['key']} on {m['task']}: mean {m['coverage68']:.4f} reads "
                   f"'{m['calibrationVerdict']}', but {detail}.")
    out.append("- So quote the parameter the user is actually inferring, never the "
               "average.")

    out += ["", "## How far apart the entries actually are", ""]
    for task in ("camelsJoint", "camelsSamJoint", "camelsCloud"):
        out += accuracy_lines(rows, task)
    if cheap and dear:
        out.append(f"- Cost per cell runs from {cheap[0]:.1f} s ({cheap[1]}) to "
                   f"{dear[0]:,.1f} s ({dear[1]}), a factor of "
                   f"{dear[0] / max(cheap[0], 1e-9):,.0f}.")
    out.append("- So among entries that work at all, compute separates them far more "
               "than accuracy does.")

    gains = [(m["infoGainNats"], e["key"], m["task"]) for e, m in rows
             if m.get("infoGainNats") is not None]
    if gains:
        gains.sort()
        worse = [g for g in gains if g[0] < 0]
        out += ["", "## Information gain over the prior, in nats", "",
                "A posterior that simply returns the prior scores exactly zero here. "
                "This is the only column that catches an entry with a good posterior "
                "mean that puts almost no density where the truth is, which neither R2 "
                "nor coverage can show.",
                "",
                "CAVEAT. A Gaussian KDE over 1000 samples, averaged over evaluation "
                "points, so a few points where the posterior misses entirely dominate "
                "it. Scott's bandwidth also assumes independent draws, true for the "
                "direct sampling entries and false for the emcee ones, whose samples "
                "are autocorrelated, so the KDE is too peaked for them and the metric "
                "is biased against them. That is exactly where the worst values sit. "
                "Order within a sampler class, never across one."]
        if worse:
            out.append(f"- {len(worse)} measured pairs are WORSE than the prior:")
            for g, k, t in worse:
                out.append(f"    - {k} on {t}, {g:+.3f} nats. Do not quote its "
                           f"uncertainties.")
        out.append(f"- Best: {gains[-1][1]} on {gains[-1][2]} at {gains[-1][0]:+.3f} "
                   f"nats. Worst: {gains[0][1]} on {gains[0][2]} at {gains[0][0]:+.3f}.")

    out += ["", "## Amortization", ""]
    npe = [r for r in rows if r[0]["engine"] == "NPE"]
    mcmc = [r for r in rows if r[0]["engine"] in ("NLE", "NRE")]
    if npe:
        out.append(f"- NPE inference: "
                   f"{min(m['inferenceSeconds'] for _, m in npe):.1f} to "
                   f"{max(m['inferenceSeconds'] for _, m in npe):.1f} s per observation.")
    if mcmc:
        out.append(f"- NLE and NRE inference: "
                   f"{min(m['inferenceSeconds'] for _, m in mcmc):.1f} to "
                   f"{max(m['inferenceSeconds'] for _, m in mcmc):,.1f} s per "
                   f"observation, because each observation needs its own MCMC run.")

    out += ["", "## Per entry, sorted by how badly calibrated", "",
            "| entry | backend | modality | verdict | tasks | worst sigma |",
            "|---|---|---|---|---|---|"]
    def worst(e):
        s = [m["calibrationSigma"] for m in e["measurements"]
             if m["calibrationSigma"] is not None]
        return min(s) if s else 0.0
    for e in sorted(entries, key=worst):
        out.append(f"| {e['key']} | {e['backend']} | {e['modality']} | "
                   f"{e['calibrationVerdict']} | {len(e['admittedTasks'])} | "
                   f"{worst(e):+.1f} |")
    return "\n".join(out) + "\n"


def main() -> None:
    zoo = json.loads(ZOO_PATH.read_text(encoding="utf-8"))
    OUT.write_text(render(zoo), encoding="utf-8")
    print(f"  wrote {OUT}")


if __name__ == "__main__":
    main()
